apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kmc-controller-leader-election
  namespace: kmc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kmc-controller-leader-election
subjects:
  - kind: ServiceAccount
    name: kmc-controller
    namespace: kmc-system
